## 认识异常

程序过程中可能有很多出错的情况，出错的原因可能是多方面的，有的是不可控的内部原因，比如内存不够了、磁盘满了，有的是不可控的外部原因，比如网络连接有问题，更多的可能是程序的编程错误，比如引用变量未初始化就直接调用实例方法。

### 常见的异常
#### NullPointerException (空指针异常)
我们先看一段代码：
```java  
package com.example;
public class ExceptionTest {
    public static void main(String[] args) {
        String s = null;
        s.indexOf("a");
        System.out.println("end");
    }
}
```
变量s没有初始化就调用其实例方法indexOf，运行，屏幕输出为：  
>Exception in thread "main" java.lang.NullPointerException
    at ExceptionTest.main(ExceptionTest.java:5)

输出是告诉我们：在ExceptionTest类的main函数中，代码第5行，出现了空指针异常(java.lang.NullPointerException)。     
**原因：**  
当执行s.indexOf("a")的时候，Java系统发现s的值为null，没有办法继续执行了，这时就启用异常处理机制，首先创建一个异常对象，这里是类NullPointerException的对象，然后查找看谁能处理这个异常，在示例代码中，没有代码能处理这个异常，Java就启用默认处理机制，那就是打印异常栈信息到屏幕，并退出程序。

####
```java
package com.example;
public class ExceptionTest {
  public static void main(String[] arg)  {
      int result= Integer.parseInt("ab3");
      System.out.println("result == " + result);
  }
}
```
>Exception in thread "main" java.lang.NumberFormatException: For input string: "ab3"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.example.ExceptionTest.main(MyClass.java:4)  

Integer.parseInt将参数转换为一个整数，并输出这个整数。参数是可能是用户输入的，我们没有办法强制用户输入什么，如果用户输的是数字，比如123，屏幕会输出123，但如果用户输的不是数字，则会出现上面的那个错误。   
根据错误信息的提示，我们来到
```java
// Integer.javad 的第580行：
throw NumberFormatException.forInputString(var0);

// NumberFormatException.java
static NumberFormatException forInputString(String var0) {
    return new NumberFormatException("For input string: \"" + var0 + "\"");
}
```
new NumberFormatException(...)是我们容易理解的，就是创建了一个类的对象，只是这个类是一个异常类。  
throw是什么意思呢？就是抛出异常，它会触发Java的异常处理机制。在之前的空指针异常中，我们没有看到throw的代码，可以认为throw是由Java虚拟机自己实现的。

### throw关键字
throw关键字可以与return关键字进行对比，return代表正常退出，throw代表异常退出，return的返回位置是确定的，就是上一级调用者，而throw后执行哪行代码则经常是不确定的，由异常处理机制动态确定。  

异常处理机制会从当前函数开始查找看谁"捕获"了这个异常，当前函数没有就查看上一层，直到主函数，如果主函数也没有，就使用默认机制，即输出异常栈信息并退出，这正是我们在屏幕输出中看到的。
